# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
   #   branches: [ "main" ]

  pull_request:
    types: [opened, reopened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr_details:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR details
        id: pr_details
        shell: pwsh
        run: |
          $prData = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json
          
          $prNumber = $prData.pull_request.number
          $prTitle = $prData.pull_request.title
          $prBody = $prData.pull_request.body
          $prState = $prData.pull_request.state
          $prAuthor = $prData.pull_request.user.login
          $prAssignees = $prData.pull_request.assignees.login -join ", "
          $prReviewers = $prData.pull_request.requested_reviewers.login -join ", "
          $repoUrl = $prData.repository.html_url
          $prUrl = "$repoUrl/pull/$prNumber"

          # Fetching modified files (using GitHub API)
          $modifiedFiles = (Invoke-RestMethod -Uri "$($prData.pull_request.url)/files" -Headers @{Authorization = "Bearer $env:GITHUB_TOKEN"}).filename -join ", "
          
          # Use echo to append variables to GITHUB_ENV
          echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
          echo "PR_TITLE=$prTitle" >> $env:GITHUB_ENV
          echo "PR_BODY=$prBody" >> $env:GITHUB_ENV
          echo "PR_STATE=$prState" >> $env:GITHUB_ENV
          echo "PR_AUTHOR=$prAuthor" >> $env:GITHUB_ENV
          echo "PR_ASSIGNEES=$prAssignees" >> $env:GITHUB_ENV
          echo "PR_REVIEWERS=$prReviewers" >> $env:GITHUB_ENV
          echo "REPO_URL=$repoUrl" >> $env:GITHUB_ENV
          echo "PR_URL=$prUrl" >> $env:GITHUB_ENV
          echo "PR_MODIFIED_FILES=$modifiedFiles" >> $env:GITHUB_ENV

      - name: Output PR details
        shell: pwsh
        run: |
          Write-Host "PR Number: ${{ env.PR_NUMBER }}"
          Write-Host "PR Title: ${{ env.PR_TITLE }}"
          Write-Host "PR Description: ${{ env.PR_BODY }}"
          Write-Host "PR State: ${{ env.PR_STATE }}"
          Write-Host "PR Author: ${{ env.PR_AUTHOR }}"
          Write-Host "PR Assignees: ${{ env.PR_ASSIGNEES }}"
          Write-Host "PR Reviewers: ${{ env.PR_REVIEWERS }}"
          Write-Host "Repository URL: ${{ env.REPO_URL }}"
          Write-Host "Pull Request URL: ${{ env.PR_URL }}"
          Write-Host "Modified Files: ${{ env.PR_MODIFIED_FILES }}"
